# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /srv/eqbeats/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /srv/eqbeats

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /srv/eqbeats/CMakeFiles /srv/eqbeats/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /srv/eqbeats/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eqbeats.fcgi

# Build rule for target.
eqbeats.fcgi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eqbeats.fcgi
.PHONY : eqbeats.fcgi

# fast build rule for target.
eqbeats.fcgi/fast:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/build
.PHONY : eqbeats.fcgi/fast

#=============================================================================
# Target rules for targets named mknews

# Build rule for target.
mknews: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mknews
.PHONY : mknews

# fast build rule for target.
mknews/fast:
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/build
.PHONY : mknews/fast

FCgiIO.o: FCgiIO.cpp.o
.PHONY : FCgiIO.o

# target to build an object file
FCgiIO.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/FCgiIO.cpp.o
.PHONY : FCgiIO.cpp.o

FCgiIO.i: FCgiIO.cpp.i
.PHONY : FCgiIO.i

# target to preprocess a source file
FCgiIO.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/FCgiIO.cpp.i
.PHONY : FCgiIO.cpp.i

FCgiIO.s: FCgiIO.cpp.s
.PHONY : FCgiIO.s

# target to generate assembly for a file
FCgiIO.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/FCgiIO.cpp.s
.PHONY : FCgiIO.cpp.s

account.o: account.cpp.o
.PHONY : account.o

# target to build an object file
account.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/account.cpp.o
.PHONY : account.cpp.o

account.i: account.cpp.i
.PHONY : account.i

# target to preprocess a source file
account.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/account.cpp.i
.PHONY : account.cpp.i

account.s: account.cpp.s
.PHONY : account.s

# target to generate assembly for a file
account.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/account.cpp.s
.PHONY : account.cpp.s

actions/account.o: actions/account.cpp.o
.PHONY : actions/account.o

# target to build an object file
actions/account.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/account.cpp.o
.PHONY : actions/account.cpp.o

actions/account.i: actions/account.cpp.i
.PHONY : actions/account.i

# target to preprocess a source file
actions/account.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/account.cpp.i
.PHONY : actions/account.cpp.i

actions/account.s: actions/account.cpp.s
.PHONY : actions/account.s

# target to generate assembly for a file
actions/account.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/account.cpp.s
.PHONY : actions/account.cpp.s

actions/login.o: actions/login.cpp.o
.PHONY : actions/login.o

# target to build an object file
actions/login.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/login.cpp.o
.PHONY : actions/login.cpp.o

actions/login.i: actions/login.cpp.i
.PHONY : actions/login.i

# target to preprocess a source file
actions/login.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/login.cpp.i
.PHONY : actions/login.cpp.i

actions/login.s: actions/login.cpp.s
.PHONY : actions/login.s

# target to generate assembly for a file
actions/login.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/login.cpp.s
.PHONY : actions/login.cpp.s

actions/registration.o: actions/registration.cpp.o
.PHONY : actions/registration.o

# target to build an object file
actions/registration.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/registration.cpp.o
.PHONY : actions/registration.cpp.o

actions/registration.i: actions/registration.cpp.i
.PHONY : actions/registration.i

# target to preprocess a source file
actions/registration.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/registration.cpp.i
.PHONY : actions/registration.cpp.i

actions/registration.s: actions/registration.cpp.s
.PHONY : actions/registration.s

# target to generate assembly for a file
actions/registration.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/registration.cpp.s
.PHONY : actions/registration.cpp.s

actions/track.o: actions/track.cpp.o
.PHONY : actions/track.o

# target to build an object file
actions/track.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/track.cpp.o
.PHONY : actions/track.cpp.o

actions/track.i: actions/track.cpp.i
.PHONY : actions/track.i

# target to preprocess a source file
actions/track.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/track.cpp.i
.PHONY : actions/track.cpp.i

actions/track.s: actions/track.cpp.s
.PHONY : actions/track.s

# target to generate assembly for a file
actions/track.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/track.cpp.s
.PHONY : actions/track.cpp.s

actions/upload.o: actions/upload.cpp.o
.PHONY : actions/upload.o

# target to build an object file
actions/upload.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/upload.cpp.o
.PHONY : actions/upload.cpp.o

actions/upload.i: actions/upload.cpp.i
.PHONY : actions/upload.i

# target to preprocess a source file
actions/upload.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/upload.cpp.i
.PHONY : actions/upload.cpp.i

actions/upload.s: actions/upload.cpp.s
.PHONY : actions/upload.s

# target to generate assembly for a file
actions/upload.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/actions/upload.cpp.s
.PHONY : actions/upload.cpp.s

comment.o: comment.cpp.o
.PHONY : comment.o

# target to build an object file
comment.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/comment.cpp.o
.PHONY : comment.cpp.o

comment.i: comment.cpp.i
.PHONY : comment.i

# target to preprocess a source file
comment.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/comment.cpp.i
.PHONY : comment.cpp.i

comment.s: comment.cpp.s
.PHONY : comment.s

# target to generate assembly for a file
comment.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/comment.cpp.s
.PHONY : comment.cpp.s

db.o: db.cpp.o
.PHONY : db.o

# target to build an object file
db.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/db.cpp.o
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/db.cpp.o
.PHONY : db.cpp.o

db.i: db.cpp.i
.PHONY : db.i

# target to preprocess a source file
db.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/db.cpp.i
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/db.cpp.i
.PHONY : db.cpp.i

db.s: db.cpp.s
.PHONY : db.s

# target to generate assembly for a file
db.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/db.cpp.s
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/db.cpp.s
.PHONY : db.cpp.s

ffmpeg.o: ffmpeg.cpp.o
.PHONY : ffmpeg.o

# target to build an object file
ffmpeg.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/ffmpeg.cpp.o
.PHONY : ffmpeg.cpp.o

ffmpeg.i: ffmpeg.cpp.i
.PHONY : ffmpeg.i

# target to preprocess a source file
ffmpeg.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/ffmpeg.cpp.i
.PHONY : ffmpeg.cpp.i

ffmpeg.s: ffmpeg.cpp.s
.PHONY : ffmpeg.s

# target to generate assembly for a file
ffmpeg.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/ffmpeg.cpp.s
.PHONY : ffmpeg.cpp.s

flac.o: flac.cpp.o
.PHONY : flac.o

# target to build an object file
flac.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/flac.cpp.o
.PHONY : flac.cpp.o

flac.i: flac.cpp.i
.PHONY : flac.i

# target to preprocess a source file
flac.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/flac.cpp.i
.PHONY : flac.cpp.i

flac.s: flac.cpp.s
.PHONY : flac.s

# target to generate assembly for a file
flac.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/flac.cpp.s
.PHONY : flac.cpp.s

html/escape.o: html/escape.cpp.o
.PHONY : html/escape.o

# target to build an object file
html/escape.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/escape.cpp.o
.PHONY : html/escape.cpp.o

html/escape.i: html/escape.cpp.i
.PHONY : html/escape.i

# target to preprocess a source file
html/escape.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/escape.cpp.i
.PHONY : html/escape.cpp.i

html/escape.s: html/escape.cpp.s
.PHONY : html/escape.s

# target to generate assembly for a file
html/escape.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/escape.cpp.s
.PHONY : html/escape.cpp.s

html/news.o: html/news.cpp.o
.PHONY : html/news.o

# target to build an object file
html/news.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/news.cpp.o
.PHONY : html/news.cpp.o

html/news.i: html/news.cpp.i
.PHONY : html/news.i

# target to preprocess a source file
html/news.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/news.cpp.i
.PHONY : html/news.cpp.i

html/news.s: html/news.cpp.s
.PHONY : html/news.s

# target to generate assembly for a file
html/news.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/news.cpp.s
.PHONY : html/news.cpp.s

html/page.o: html/page.cpp.o
.PHONY : html/page.o

# target to build an object file
html/page.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/page.cpp.o
.PHONY : html/page.cpp.o

html/page.i: html/page.cpp.i
.PHONY : html/page.i

# target to preprocess a source file
html/page.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/page.cpp.i
.PHONY : html/page.cpp.i

html/page.s: html/page.cpp.s
.PHONY : html/page.s

# target to generate assembly for a file
html/page.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/page.cpp.s
.PHONY : html/page.cpp.s

html/redirect.o: html/redirect.cpp.o
.PHONY : html/redirect.o

# target to build an object file
html/redirect.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/redirect.cpp.o
.PHONY : html/redirect.cpp.o

html/redirect.i: html/redirect.cpp.i
.PHONY : html/redirect.i

# target to preprocess a source file
html/redirect.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/redirect.cpp.i
.PHONY : html/redirect.cpp.i

html/redirect.s: html/redirect.cpp.s
.PHONY : html/redirect.s

# target to generate assembly for a file
html/redirect.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/redirect.cpp.s
.PHONY : html/redirect.cpp.s

html/track.o: html/track.cpp.o
.PHONY : html/track.o

# target to build an object file
html/track.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/track.cpp.o
.PHONY : html/track.cpp.o

html/track.i: html/track.cpp.i
.PHONY : html/track.i

# target to preprocess a source file
html/track.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/track.cpp.i
.PHONY : html/track.cpp.i

html/track.s: html/track.cpp.s
.PHONY : html/track.s

# target to generate assembly for a file
html/track.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/track.cpp.s
.PHONY : html/track.cpp.s

html/user.o: html/user.cpp.o
.PHONY : html/user.o

# target to build an object file
html/user.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/user.cpp.o
.PHONY : html/user.cpp.o

html/user.i: html/user.cpp.i
.PHONY : html/user.i

# target to preprocess a source file
html/user.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/user.cpp.i
.PHONY : html/user.cpp.i

html/user.s: html/user.cpp.s
.PHONY : html/user.s

# target to generate assembly for a file
html/user.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/html/user.cpp.s
.PHONY : html/user.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/main.cpp.s
.PHONY : main.cpp.s

mknews.o: mknews.cpp.o
.PHONY : mknews.o

# target to build an object file
mknews.cpp.o:
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/mknews.cpp.o
.PHONY : mknews.cpp.o

mknews.i: mknews.cpp.i
.PHONY : mknews.i

# target to preprocess a source file
mknews.cpp.i:
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/mknews.cpp.i
.PHONY : mknews.cpp.i

mknews.s: mknews.cpp.s
.PHONY : mknews.s

# target to generate assembly for a file
mknews.cpp.s:
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/mknews.cpp.s
.PHONY : mknews.cpp.s

news.o: news.cpp.o
.PHONY : news.o

# target to build an object file
news.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/news.cpp.o
.PHONY : news.cpp.o

news.i: news.cpp.i
.PHONY : news.i

# target to preprocess a source file
news.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/news.cpp.i
.PHONY : news.cpp.i

news.s: news.cpp.s
.PHONY : news.s

# target to generate assembly for a file
news.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/news.cpp.s
.PHONY : news.cpp.s

routing.o: routing.cpp.o
.PHONY : routing.o

# target to build an object file
routing.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/routing.cpp.o
.PHONY : routing.cpp.o

routing.i: routing.cpp.i
.PHONY : routing.i

# target to preprocess a source file
routing.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/routing.cpp.i
.PHONY : routing.cpp.i

routing.s: routing.cpp.s
.PHONY : routing.s

# target to generate assembly for a file
routing.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/routing.cpp.s
.PHONY : routing.cpp.s

session.o: session.cpp.o
.PHONY : session.o

# target to build an object file
session.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/session.cpp.o
.PHONY : session.cpp.o

session.i: session.cpp.i
.PHONY : session.i

# target to preprocess a source file
session.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/session.cpp.i
.PHONY : session.cpp.i

session.s: session.cpp.s
.PHONY : session.s

# target to generate assembly for a file
session.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/session.cpp.s
.PHONY : session.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/timer.cpp.s
.PHONY : timer.cpp.s

track.o: track.cpp.o
.PHONY : track.o

# target to build an object file
track.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/track.cpp.o
.PHONY : track.cpp.o

track.i: track.cpp.i
.PHONY : track.i

# target to preprocess a source file
track.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/track.cpp.i
.PHONY : track.cpp.i

track.s: track.cpp.s
.PHONY : track.s

# target to generate assembly for a file
track.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/track.cpp.s
.PHONY : track.cpp.s

user.o: user.cpp.o
.PHONY : user.o

# target to build an object file
user.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/user.cpp.o
.PHONY : user.cpp.o

user.i: user.cpp.i
.PHONY : user.i

# target to preprocess a source file
user.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/user.cpp.i
.PHONY : user.cpp.i

user.s: user.cpp.s
.PHONY : user.s

# target to generate assembly for a file
user.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/user.cpp.s
.PHONY : user.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/eqbeats.fcgi.dir/build.make CMakeFiles/eqbeats.fcgi.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/mknews.dir/build.make CMakeFiles/mknews.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... eqbeats.fcgi"
	@echo "... mknews"
	@echo "... rebuild_cache"
	@echo "... FCgiIO.o"
	@echo "... FCgiIO.i"
	@echo "... FCgiIO.s"
	@echo "... account.o"
	@echo "... account.i"
	@echo "... account.s"
	@echo "... actions/account.o"
	@echo "... actions/account.i"
	@echo "... actions/account.s"
	@echo "... actions/login.o"
	@echo "... actions/login.i"
	@echo "... actions/login.s"
	@echo "... actions/registration.o"
	@echo "... actions/registration.i"
	@echo "... actions/registration.s"
	@echo "... actions/track.o"
	@echo "... actions/track.i"
	@echo "... actions/track.s"
	@echo "... actions/upload.o"
	@echo "... actions/upload.i"
	@echo "... actions/upload.s"
	@echo "... comment.o"
	@echo "... comment.i"
	@echo "... comment.s"
	@echo "... db.o"
	@echo "... db.i"
	@echo "... db.s"
	@echo "... ffmpeg.o"
	@echo "... ffmpeg.i"
	@echo "... ffmpeg.s"
	@echo "... flac.o"
	@echo "... flac.i"
	@echo "... flac.s"
	@echo "... html/escape.o"
	@echo "... html/escape.i"
	@echo "... html/escape.s"
	@echo "... html/news.o"
	@echo "... html/news.i"
	@echo "... html/news.s"
	@echo "... html/page.o"
	@echo "... html/page.i"
	@echo "... html/page.s"
	@echo "... html/redirect.o"
	@echo "... html/redirect.i"
	@echo "... html/redirect.s"
	@echo "... html/track.o"
	@echo "... html/track.i"
	@echo "... html/track.s"
	@echo "... html/user.o"
	@echo "... html/user.i"
	@echo "... html/user.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mknews.o"
	@echo "... mknews.i"
	@echo "... mknews.s"
	@echo "... news.o"
	@echo "... news.i"
	@echo "... news.s"
	@echo "... routing.o"
	@echo "... routing.i"
	@echo "... routing.s"
	@echo "... session.o"
	@echo "... session.i"
	@echo "... session.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... track.o"
	@echo "... track.i"
	@echo "... track.s"
	@echo "... user.o"
	@echo "... user.i"
	@echo "... user.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

