#!/bin/bash

QUEUE="${1:-/var/spool/eqbeats/feature.queue}"

tid="$(head -n 1 "$QUEUE" | cut -d ' ' -f 1)"
[ -z "$tid" ] && exit 1

psql -c "INSERT INTO featured_tracks (track_id, date) VALUES ($tid, 'now')"

tail -n +2 "$QUEUE" > "${QUEUE}.tail"
mv "${QUEUE}.tail" "$QUEUE"
